### ISSUE TITLE
invalid address error in create task action

### ISSUE THREAD

**Issue by alifakoor** [dappuniversity/eth-todo-list#5]
Hi dear Gregory
First off, I'm so thankful for dappuniversity, it is so cool.
I'm new to Blockchain so I read your article about creating a todo list with Ethereum
I wrote my codes exactly you said in your article, but I  got an error in the 'formatter.js' file when I want to submit a new task.
This is the error:
`Uncaught (in promise) Error: invalid address`
Can you help me with that, please?

**Comment by stonekase** [comment]
The below is the same issue  i guess. Hope you used the same version of libraries in the tutorial ?


https://github.com/dappuniversity/eth-todo-list/issues/4#issue-700629113

**Comment by alifakoor** [comment]
> The below is the same issue i guess. Hope you used the same version of libraries in the tutorial ?
> 
> [#4 (comment)](https://github.com/dappuniversity/eth-todo-list/issues/4#issue-700629113)

Thank you @stonekase 
it's solved.
